dataset:
  rows: 50
  composition_percentage:
    duplicates: 0
    missing_fields: 0
    unprocessable_rows: 0
data_blocker:
  type: 'sleep'
  configuration:
    sleep_time_range_seconds:
      from: 1
      to: 7
entity:
  type: visit
  configuration:
    start_time: '2023-11-01T00:00:00Z'
generator:
  type: continuous
writer:
  type: postgresql
  configuration:
    host: 'postgres'
    dbname: 'generator'
    db_schema: 'generator_schema'
    user: 'postgres'
    password: 'postgres'
    table_name: 'visits'
    table_columns: ['visit_id', 'event_time', 'user_id', 'page']
    row_fields_to_insert: ['visit_id', 'event_time', 'user_id', 'page']
