dataset:
  rows: 1000
  composition_percentage:
    duplicates: 25
    missing_fields: 0
    unprocessable_rows: 0
data_blocker:
  type: sleep
  configuration:
    sleep_time_range_seconds:
      from: 2
      to: 6
entity:
  type: visit
  configuration:
    start_time: 2023-11-24T00:00:00Z
generator:
  type: one-shot
writer:
  type: json
  configuration:
    output_path: '/tmp/abc'
    clean_path: true